version: 2.1
orbs:
  utils: arrai/utils@1.5.0
executors:
  python38:
    environment:
        LANG: C.UTF-8
    docker:
     - image: circleci/python:3.8
jobs:
  deepcode:
    parameters:
      wd:
        type: string
        default: ./${CIRCLE_PROJECT_REPONAME}
      files:
        type: string
        default: "."
    executor: python38
    steps:
      - checkout
      - utils/add_ssh_config
      - run:
          name: Install additional OS packages
          command: sudo apt-get install rsync
      - run:
          name: Install DeepCode CLI
          command: |
            cd <<parameters.wd>>
            python3 -m venv ${HOME}/.venv/
            . ~/.venv/bin/activate
            echo "source ${HOME}/.venv/bin/activate" >> $BASH_ENV
            pip install deepcode
      - run:
          name: Run DeepCode CLI
          command: |
            cd <<parameters.wd>>
            deepcode analyze -p <<parameters.files>> > results.json
      - run:
          name: Determine issue severity
          command: |
            DEEPCODE_SEVERITY="$(python -c 'import sys;import json;print(max([suggestion["severity"] for suggestion in json.load(open("results.json", "r"))["results"]["suggestions"].values()] or [0]))')"
            if [ "${DEEPCODE_SEVERITY}" = "1" ]; then
                DEEPCODE_STATUS_TEXT="info"
                DEEPCODE_STATUS_COLOUR="yellow"
            elif [ "${DEEPCODE_SEVERITY}" = "2" ]; then
                DEEPCODE_STATUS_TEXT="warning"
                DEEPCODE_STATUS_COLOUR="orange"
            elif [ "${DEEPCODE_SEVERITY}" = "3" ]; then
                DEEPCODE_STATUS_TEXT="critical"
                DEEPCODE_STATUS_COLOUR="red"
            else
                DEEPCODE_STATUS_TEXT="passed"
                DEEPCODE_STATUS_COLOUR="brightgreen"
            fi
          when: always
      - utils/make_status_shield:
          status: ${DEEPCODE_STATUS_TEXT}
          color: ${DEEPCODE_STATUS_COLOUR}
          logo: circleci
          when: always
      - utils/rsync_file:
          file: ~/status.svg
          remote_file: $CIRCLE_BRANCH.$CIRCLE_JOB.svg
          host: docs
          when: always
