version: 2.1
orbs:
  utils: arrai/utils@1.3.0
executors:
  python37:
    environment:
        LANG: en_US.UTF-8
    docker:
     - image: circleci/python:3.7.2
  python36:
    environment:
        LANG: en_US.UTF-8
    docker:
     - image: circleci/python:3.6.8
  python35:
    environment:
        LANG: en_US.UTF-8
    docker:
     - image: circleci/python:3.5.6
  python27:
    environment:
        LANG: en_US.UTF-8
    docker:
     - image: circleci/python:2.7.16
jobs:
  flake8:
    parameters:
      wd:
        type: string
        default: ./${CIRCLE_PROJECT_REPONAME}
      executor:
        type: executor
        default: python36
    executor: <<parameters.executor>>
    steps:
      - checkout
      - utils/add_ssh_config
      - run: sudo apt-get install rsync
      - setup_flake8
      - flake8_errors:
          wd: <<parameters.wd>>
      - utils/make_status_shield:
          when: on_fail
          status: errors
          color: red
          logo: python
      - flake8_warnings:
          wd: <<parameters.wd>>
      - utils/make_status_shield:
          when: always
          status: warnings
          color: orange
          logo: python
          preserve: true
      - utils/make_status_shield:
          when: on_success
          status: passed
          color: brightgreen
          logo: python
      - utils/rsync_file:
          when: always
          file: ~/status.svg
          remote_file: $CIRCLE_BRANCH.$CIRCLE_JOB.svg
          host: docs
commands:
  setup_flake8:
    description: "Set up a python virtual environment to run flake8"
    steps:
      - run:
          name: "Set up python virtual environment."
          command: |
            if [ "${PYTHON_VERSION}" == "2.7.16" ]; then
                virtualenv ${HOME}/.venv/
            else
                python3 -m venv ${HOME}/.venv/
            fi
            . ~/.venv/bin/activate
            echo "source ${HOME}/.venv/bin/activate" >> $BASH_ENV
            pip install flake8 | cat; test ${PIPESTATUS[0]} -eq 0
  flake8_errors:
    description: "Run flake8, checking for errors only."
    parameters:
      wd:
        type: string
    steps:
      - run:
          name: "Check for errors."
          command: |
            cd <<parameters.wd>>
            flake8 --extend-ignore="$FLAKE8_WARNINGS"
  flake8_warnings:
    description: "Run flake8, checking for warnings only."
    parameters:
      wd:
        type: string
    steps:
      - run:
          name: "Check for warnings."
          command: |
            cd <<parameters.wd>>
            flake8 --extend-ignore="$FLAKE8_ERRORS"
          when: always
