version: 2.1
orbs:
  utils: arrai/utils@1.2.0
jobs:
  flake8:
    parameters:
      wd:
        type: string
        default: ~/repo
    executor: flake8_executor
    steps:
      - checkout
      - utils/add_ssh_config
      - run: sudo apt-get install rsync
      - setup_flake8
      - flake8_errors:
          wd: <<parameters.wd>>
      - utils/make_status_shield:
          when: on_fail
          status: errors
          color: red
          logo: python
      - flake8_warnings:
          wd: <<parameters.wd>>
      - utils/make_status_shield:
          when: always
          status: warnings
          color: orange
          logo: python
          preserve: true
      - utils/make_status_shield:
          when: on_success
          status: passed
          color: brightgreen
          logo: python
      - utils/rsync_file:
          when: always
          file: ~/status.svg
          remote_file: $CIRCLE_BRANCH.$CIRCLE_JOB.svg
          host: docs
commands:
  setup_flake8:
    steps:
      - run:
          name: Setup flake8
          command: |
            python3 -m venv ~/.venv/
            . ~/.venv/bin/activate
            pip install flake8 | cat; test ${PIPESTATUS[0]} -eq 0
  flake8_errors:
    parameters:
      wd:
        type: string
    steps:
      - run:
          name: Flake8 errors
          command: |
            cd <<parameters.wd>>
            . ~/.venv/bin/activate
            flake8 --extend-ignore="$FLAKE8_WARNINGS"
  flake8_warnings:
    parameters:
      wd:
        type: string
    steps:
      - run:
          name: Flake8 warnings
          command: |
            cd <<parameters.wd>>
            . ~/.venv/bin/activate
            flake8 --extend-ignore="$FLAKE8_ERRORS"
          when: always
executors:
  flake8_executor:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.8
    environment:
      LANG: en_US.UTF-8
